name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# for security reasons the github actions are pinned to specific release versions
jobs:
  link_checker:
    name: link checker
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.5.0

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.7.0
        with:
          # skip the jekyll files
          args: --exclude-path './_includes/*.html' './**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
