name: Release docs

on:
  push:
    # only for version x.x.x releases and release candidates
    tags:
      - v?.?.?*
  workflow_dispatch:

# for security reasons the github actions are pinned to specific release versions
jobs:
  export_docs:
    name: Export PDF and ePub
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v4.1.1

      - name: Fix up markdown
        run: |
          find release -name "*.md" -exec sed -i '' "s|permalink: /draft/|permalink: /release/|g" {} +
          find release -name "*.md" -exec sed -i '' "/The OWASP Developer Guide is a community effort/d" {} +
          find release -name "*.md" -exec sed -i '' "/edit on GitHub/d" {} +
          find release -name "*.md" -exec sed -i '' "/www-project-developer-guide\/issues\/new?labels/d" {} +
          find release -name "*.md" -exec sed -i '' "/www-project-developer-guide\/blob\/main/d" {} +

      - name: Combine markdown
        run: |
          tail --lines=+14 -q $(find release -name "*[0-9]*.md" | sort) > release.markdown
          mkdir -p publish

      - name: Export to pdf
        uses: docker://pandoc/latex:3.1
        with:
          args: >-
            --from=markdown
            --output=publish/OWASP_Developer_Guide.pdf
            --resource-path="release/assets/images:release/assets:release"
            release/title.pdf.yaml
            release.markdown

      - name: Export to epub
        uses: docker://pandoc/latex:3.1
        with:
          args: >-
            --from=markdown
            --output=publish/OWASP_Developer_Guide.epub
            --resource-path="release/assets/images:release/assets:release"
            release/title.yaml
            release.markdown

      - name: Save pdfs and epubs
        uses: actions/upload-artifact@v4.3.0
        with:
          name: export-docs
          path: publish
